language: c
compiler: gcc

env:
  - TARGET="go-1.7.1"
  - TARGET="node-v4.6.0"
  - TARGET="perl-5.24.0"
  - TARGET="php-7.0.10"
  - TARGET="python-3.5.2"
  - TARGET="ruby-2.3.1"

script: "./${TARGET/-*}-install ${TARGET/*-} ${TARGET}"
